# Generated by Django 4.1.3 on 2022-12-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.grouptest', verbose_name='Набор тестов'),
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now=True, verbose_name='Дата прохождения')),
                ('answers', models.CharField(max_length=128, verbose_name='Ответы')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizApp.questions', verbose_name='Вопрос')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizApp.grouptest', verbose_name='Тест')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
