# Generated by Django 4.1.3 on 2022-12-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_alter_useranswers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='grouptest',
            options={'verbose_name': 'Набор тестов', 'verbose_name_plural': 'Наборы тестов'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='useranswers',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователя'},
        ),
    ]
